### Login to be able to create notes
POST {{LOGIN_URL}}
Content-Type: application/json

{
  "username": "root",
  "password": "salainen"
}

> {% client.global.set("auth_token", response.body.token); %}

### Get all blogs
GET {{API_URL}}
Accept: application/json

### Create new blog entry
POST {{API_URL}}
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "My awesome blog post",
  "author": "Simon the great",
  "url": "www.example.com",
  "likes": 500
}

### Create new blog entry
PUT {{API_URL}}/5a422ba71b54a676234d27fb
Content-Type: application/json

{
  "likes": 2
}