### Add new note
POST {{BASE_URL}}
Content-Type: application/json

{
  "content": "I am testing the REST-api",
  "important": true
}

### Get node with specific id
GET http://localhost:3001/api/notes/6262d4a54b27c24f2bc56ee0
Accept: application/json

### Get node using malformed id
GET http://localhost:3001/api/notes/1
Accept: application/json

### Delete node with malformed id
DELETE {{BASE_URL}}/1

### Delete node with specific id
DELETE {{BASE_URL}}/6263048d4f9fe30b639cc7d5

### Get all notes
GET {{BASE_URL}}

