### Add new note
POST {{NOTES_BASE_URL}}
Content-Type: application/json

{
  "content": "I am testing the REST-api",
  "important": true,
  "userId": "62ece8c6f5f3038ec40293e3"
}

### Add new note with too short content
POST {{NOTES_BASE_URL}}
Content-Type: application/json

{
  "content": "I am",
  "important": true
}

### Add new note with missing content
POST {{NOTES_BASE_URL}}
Content-Type: application/json

{
  "important": true
}

### Get node with specific id
GET http://localhost:3001/api/notes/6262d4a54b27c24f2bc56ee0
Accept: application/json

### Get node using malformed id
GET http://localhost:3001/api/notes/1
Accept: application/json

### Delete node with malformed id
DELETE {{NOTES_BASE_URL}}/1

### Delete node with specific id
DELETE {{NOTES_BASE_URL}}/6263048d4f9fe30b639cc7d5

### Get all notes
GET {{NOTES_BASE_URL}}

### Get all users
GET {{USERS_BASE_URL}}

### Add new user
POST {{USERS_BASE_URL}}
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salainen"
}