POST {{BASE_URL}}
Content-Type: application/json

{
  "content": "I am testing the REST-api",
  "important": true
}

###
GET http://localhost:3001/api/notes/2
Accept: application/json

###

DELETE {{BASE_URL}}/1

###
// Get all
GET {{BASE_URL}}

