### Create person with all data
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "123"
}

### Create person with too short name
POST {{API_URL}}
Content-Type: application/json

{
  "name": "J",
  "number": "123"
}

### Create person with missing name
POST {{API_URL}}
Content-Type: application/json

{
  "number": "123"
}

### Create person with missing number
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John"
}

###
GET {{BASE_URL}}/info
Accept: text/html

### All persons
GET {{API_URL}}
Accept: application/json

### Find person by id
GET {{API_URL}}/6262e92834246599ccb816ce
Accept: application/json

### Find person by malformed id
GET {{API_URL}}/1
Accept: application/json

### Send request to non existing endpoint
GET {{BASE_URL}}/not_existing

### Delete with malformed id
DELETE {{API_URL}}/1

### Delete by id
DELETE {{API_URL}}/62630b845c915ef14f8162a3

### Update person with malformed id
PUT {{API_URL}}/1
Content-Type: application/json

{
  "name": "John",
  "number": "123"
}

### Update person
PUT {{API_URL}}/6262e92834246599ccb816ce
Content-Type: application/json

{
  "name": "John",
  "number": "123-456789"
}