### Create person with all data 1
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "12345678"
}

### Create person with all data 2
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John2",
  "number": "09-12345"
}

### Create person with all data 3
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John3",
  "number": "040-22334455"
}

### Create person with invalid name and number
POST {{API_URL}}
Content-Type: application/json

{
  "name": "Jo",
  "number": "12345"
}

### Create person with invalid number 1
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "1234567"
}

### Create person with invalid number 2
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "1-22334455"
}

### Create person with invalid number 3
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "10-22-334455"
}

### Create person with invalid number 4
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "10-     "
}

### Create person with too short name
POST {{API_URL}}
Content-Type: application/json

{
  "name": "J",
  "number": "123456789"
}

### Create person with missing name
POST {{API_URL}}
Content-Type: application/json

{
  "number": "123456789"
}

### Create person with missing number
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John"
}

###
GET {{BASE_URL}}/info
Accept: text/html

### All persons
GET {{API_URL}}
Accept: application/json

### Find person by id
GET {{API_URL}}/6262e92834246599ccb816ce
Accept: application/json

### Find person by malformed id
GET {{API_URL}}/1
Accept: application/json

### Send request to non existing endpoint
GET {{BASE_URL}}/not_existing

### Delete with malformed id
DELETE {{API_URL}}/1

### Delete by id
DELETE {{API_URL}}/62630b845c915ef14f8162a3

### Update person with malformed id
PUT {{API_URL}}/1
Content-Type: application/json

{
  "name": "John",
  "number": "123465789"
}

### Update person
PUT {{API_URL}}/6262e92834246599ccb816ce
Content-Type: application/json

{
  "name": "John",
  "number": "123-456789"
}