### Create person with all data
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John",
  "number": "123"
}

### Create person with missing name
POST {{API_URL}}
Content-Type: application/json

{
  "number": "123"
}

### Create person with missing number
POST {{API_URL}}
Content-Type: application/json

{
  "name": "John"
}

###
GET {{BASE_URL}}/info
Accept: text/html

### All persons
GET {{API_URL}}
Accept: application/json

###

### Find person by id
GET {{API_URL}}/6262e92834246599ccb816ce
Accept: application/json

###

DELETE {{API_URL}}/1
Accept: application/json

###

